### PR TITLE
1. migrate changes from previous branch to the current one; 2. display markers and clusters on the map according to different tabs selected

### PR DESCRIPTION
**Pull request by Zhining-ht**
1. migrate changes from the previous branch to the current one
2. implement communication between parent component and child component; 
3. display markers and clusters on the map according to different tabs selected

### CODE REVIEW

**Comment by ThomasThelen** [comment]
This looks great! Thanks for fixing up that commit log.

Can we remove the commented out code [here](https://github.com/KnowWhereGraph/kwg-faceted-search/pull/308/files#diff-6a6aaa3eca70c545eb4ce3c781d5cda118a726b465a06f98654bfb1df9c161e9R19), [here](https://github.com/KnowWhereGraph/kwg-faceted-search/pull/308/files#diff-6a6aaa3eca70c545eb4ce3c781d5cda118a726b465a06f98654bfb1df9c161e9R42), and [here](https://github.com/KnowWhereGraph/kwg-faceted-search/pull/308/files#diff-6a6aaa3eca70c545eb4ce3c781d5cda118a726b465a06f98654bfb1df9c161e9R103)?

Also, can you remove the console log statements? We don't want those getting into production.

I also see a few empty white spaces [here](https://github.com/KnowWhereGraph/kwg-faceted-search/pull/308/files#diff-6a6aaa3eca70c545eb4ce3c781d5cda118a726b465a06f98654bfb1df9c161e9R148) that can be removed.


I noticed that the map visualization changed in this PR too. The image below is what we currently have in production. The image below it is what the map looks like after this PR. Is there any way we can keep it looking the same in this PR?
Screen Shot 2022-07-20 at 1 58 19 PM
Screen Shot 2022-07-20 at 1 58 47 PM

**Comment by ThomasThelen** [comment]
During testing I found that the map doesn't re-center when switching tabs or changing the results

To Reproduce:
1. View the hazards tab
2. View the People tab
3. Note that the map has new data, but hasn't re-centered

To Reproduce:
1. View the hazards tab
2. Click 'Next' on the paginator to view more results
3. Note that the map didn't re-center

**Comment by Zhining-ht** [comment]
> During testing I found that the map doesn't re-center when switching tabs or changing the results
> 
> To Reproduce:
> 
> 1. View the hazards tab
> 2. View the People tab
> 3. Note that the map has new data, but hasn't re-centered
> 
> To Reproduce:
> 
> 1. View the hazards tab
> 2. Click 'Next' on the paginator to view more results
> 3. Note that the map didn't re-center

The map can be re-cented so that clusters can be the focus on the map

**Comment by ThomasThelen** [comment]
This definitely fixes the issue I was previously having. Just a few things to tidy up,
I see some newly commented out code that we should remove across all the files.
There are also a few new console log statements that we should remove before merging.
Can we also add jsdoc style comments to all of the new functions (like `displayClustersForTab`)?

**Pull request merged**
